name: npm publish

on:
  push:
    tags:
      - 'v*.*.*'   # z.B. v0.6.2

permissions:
  contents: read
  id-token: write   # optional für provenance

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Use Node 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'

      - name: Install deps (prod preferred)
        run: npm ci

      # Optional: Tests/Build
      # - run: npm test
      # - run: npm run build

      - name: Configure npm auth
        run: |
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Verify version matches tag
        run: |
          PKG_VERSION=$(node -p "require('./package.json').version")
          TAG_VERSION=${GITHUB_REF_NAME#v}
          if [ "$PKG_VERSION" != "$TAG_VERSION" ]; then
            echo "package.json version ($PKG_VERSION) != tag ($TAG_VERSION)"
            exit 1
          fi

      - name: Publish to npm
        run: npm publish --access public --provenance
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
